### ISSUE TITLE
Calling non-final function updateUI in constructor 

### ISSUE THREAD

**Issue by zrj99** [aterai/kotlin-swing-tips#1]
Error in AccordionPanel/src/main/kotlin/example/App.kt Line 73: override fun updateUI()
To correct this error, just modify Line 73-74 from
override fun updateUI() {
  supper.updateUI()
  val l = ....
  ...
}

to

init {
  val l = ....
  ...
}

Here is some info:
Calling non-final function updateUI in constructor 
Inspection info: Reports unsafe operations with this during object construction including:
Accessing a non-final property during class initialization: from a constructor or property initialization
Calling a non-final function during class initialization
Using this as a function argument in a constructor of a non-final class
If other classes inherit from the given class, they may not be fully initialized at the moment when an unsafe operation is carried out.
Example:
  abstract class Base {
      val code = calculate()
      abstract fun calculate(): Int
  }

  class Derived(private val x: Int) : Base() {
      override fun calculate() = x
  }

  fun testIt() {
      println(Derived(42).code) // Expected: 42, actual: 0
  }

**Comment by aterai** [comment]
Thank you for pointing this out. We will make the change.
